language: csharp
solution: Simple-Game/SimpleGame.sln 
install:
  - nuget restore Simple-Game/SimpleGame.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Simple-Game/SimpleGame.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./SimpleGameTests/bin/Release/SimpleGameTests.dll
notifications:
  hipchat: c461d3008b0a1c51e2953a2833876e@1676686